/* ============================================================
   WallVibe — Pixel Empire Storefront JS
   Generated by storefront_generator.py — DO NOT EDIT BY HAND
   ============================================================ */

(function() {
  "use strict";

  // ---- Theme Toggle ----
  const themeToggle = document.querySelector(".theme-toggle");
  const html = document.documentElement;

  function setTheme(theme) {
    html.setAttribute("data-theme", theme);
    localStorage.setItem("pe-theme", theme);
  }

  // Init from localStorage or default dark
  const savedTheme = localStorage.getItem("pe-theme") || "dark";
  setTheme(savedTheme);

  if (themeToggle) {
    themeToggle.addEventListener("click", function() {
      const current = html.getAttribute("data-theme");
      setTheme(current === "dark" ? "light" : "dark");
    });
  }

  // ---- Mobile Menu ----
  const menuBtn = document.getElementById("mobile-menu-btn");
  const mobileNav = document.getElementById("mobile-nav");

  if (menuBtn && mobileNav) {
    menuBtn.addEventListener("click", function() {
      const isOpen = mobileNav.classList.toggle("open");
      menuBtn.setAttribute("aria-expanded", isOpen);
    });

    // Close on link click
    mobileNav.querySelectorAll("a").forEach(function(a) {
      a.addEventListener("click", function() {
        mobileNav.classList.remove("open");
        menuBtn.setAttribute("aria-expanded", "false");
      });
    });
  }

  // ---- Floating Pixels ----
  function createFloatingPixels() {
    var container = document.querySelector(".floating-pixels");
    if (!container) return;
    var count = window.innerWidth < 768 ? 15 : 30;
    for (var i = 0; i < count; i++) {
      var pixel = document.createElement("div");
      pixel.className = "floating-pixel";
      var size = Math.random() * 4 + 2;
      pixel.style.width = size + "px";
      pixel.style.height = size + "px";
      pixel.style.left = Math.random() * 100 + "%";
      pixel.style.animationDuration = (Math.random() * 15 + 10) + "s";
      pixel.style.animationDelay = (Math.random() * 10) + "s";
      pixel.style.opacity = (Math.random() * 0.15 + 0.05).toString();
      container.appendChild(pixel);
    }
  }
  createFloatingPixels();

  // ---- Reveal on Scroll (IntersectionObserver) ----
  function initReveal() {
    var els = document.querySelectorAll(".reveal");
    if (!els.length) return;
    if (!("IntersectionObserver" in window)) {
      els.forEach(function(el) { el.classList.add("visible"); });
      return;
    }
    var observer = new IntersectionObserver(function(entries) {
      entries.forEach(function(entry) {
        if (entry.isIntersecting) {
          entry.target.classList.add("visible");
          observer.unobserve(entry.target);
        }
      });
    }, { threshold: 0.1, rootMargin: "0px 0px -40px 0px" });
    els.forEach(function(el) { observer.observe(el); });
  }
  initReveal();

  // ---- FAQ Accordion ----
  document.querySelectorAll(".faq-question").forEach(function(btn) {
    btn.addEventListener("click", function() {
      var item = this.closest(".faq-item");
      var wasOpen = item.classList.contains("open");
      // Close all first
      document.querySelectorAll(".faq-item.open").forEach(function(openItem) {
        openItem.classList.remove("open");
      });
      if (!wasOpen) item.classList.add("open");
    });
  });

  // ---- Animated Savings Counter ----
  function animateSavingsCounter() {
    var el = document.querySelector(".savings-amount");
    if (!el) return;
    var target = parseFloat(el.getAttribute("data-target"));
    if (isNaN(target)) return;
    var duration = 2000;
    var start = 0;
    var startTime = null;

    function step(ts) {
      if (!startTime) startTime = ts;
      var progress = Math.min((ts - startTime) / duration, 1);
      // Ease out cubic
      var eased = 1 - Math.pow(1 - progress, 3);
      var current = start + (target - start) * eased;
      el.textContent = "$" + current.toFixed(2);
      if (progress < 1) requestAnimationFrame(step);
    }

    // Trigger on scroll into view
    if ("IntersectionObserver" in window) {
      var obs = new IntersectionObserver(function(entries) {
        if (entries[0].isIntersecting) {
          requestAnimationFrame(step);
          obs.disconnect();
        }
      }, { threshold: 0.5 });
      obs.observe(el);
    } else {
      requestAnimationFrame(step);
    }
  }
  animateSavingsCounter();

  // ---- Page Transition (pixel dissolve) ----
  function initPageTransition() {
    var overlay = document.querySelector(".page-transition");
    if (!overlay) return;

    // Generate pixel grid cells
    for (var i = 0; i < 400; i++) {
      var px = document.createElement("div");
      px.className = "px";
      px.style.animationDelay = (Math.random() * 0.4) + "s";
      overlay.appendChild(px);
    }

    // Remove transition on page load
    overlay.classList.add("active");

    document.querySelectorAll('a[href^="http"], a[href$=".html"]').forEach(function(link) {
      if (link.hostname !== window.location.hostname && link.getAttribute("href").indexOf("http") === 0) return;
      link.addEventListener("click", function(e) {
        var href = this.getAttribute("href");
        if (href.startsWith("#")) return;
        e.preventDefault();
        // Reverse animation: fill in pixels
        overlay.querySelectorAll(".px").forEach(function(px) {
          px.style.animation = "none";
          px.offsetHeight; // reflow
          px.style.opacity = "0";
          px.style.animation = "pixelDissolveFill " + (0.3 + Math.random() * 0.3) + "s ease forwards";
          px.style.animationDelay = (Math.random() * 0.3) + "s";
        });

        // Add fill keyframe dynamically
        if (!document.getElementById("px-fill-style")) {
          var style = document.createElement("style");
          style.id = "px-fill-style";
          style.textContent = "@keyframes pixelDissolveFill { 0% { opacity: 0; } 100% { opacity: 1; } }";
          document.head.appendChild(style);
        }

        setTimeout(function() { window.location.href = href; }, 500);
      });
    });
  }
  initPageTransition();

  // ---- Confetti for Success Page ----
  function initConfetti() {
    var canvas = document.getElementById("confetti-canvas");
    if (!canvas) return;
    var ctx = canvas.getContext("2d");
    canvas.width = window.innerWidth;
    canvas.height = window.innerHeight;

    var accent = "#f97316";
    var colors = [accent, "#ff6b9d", "#fbbf24", "#34d399", "#818cf8", "#f472b6", "#22d3ee"];
    var particles = [];

    for (var i = 0; i < 150; i++) {
      particles.push({
        x: Math.random() * canvas.width,
        y: Math.random() * canvas.height - canvas.height,
        w: Math.random() * 6 + 3,
        h: Math.random() * 6 + 3,
        color: colors[Math.floor(Math.random() * colors.length)],
        vx: (Math.random() - 0.5) * 3,
        vy: Math.random() * 3 + 2,
        rotation: Math.random() * 360,
        rotationSpeed: (Math.random() - 0.5) * 10,
        opacity: 1
      });
    }

    var frame = 0;
    var maxFrames = 300;

    function draw() {
      ctx.clearRect(0, 0, canvas.width, canvas.height);
      frame++;

      for (var i = 0; i < particles.length; i++) {
        var p = particles[i];
        p.x += p.vx;
        p.y += p.vy;
        p.rotation += p.rotationSpeed;
        p.vy += 0.05; // gravity

        if (frame > maxFrames * 0.7) {
          p.opacity -= 0.01;
        }

        if (p.opacity <= 0) continue;

        ctx.save();
        ctx.translate(p.x, p.y);
        ctx.rotate(p.rotation * Math.PI / 180);
        ctx.globalAlpha = Math.max(0, p.opacity);
        ctx.fillStyle = p.color;
        // Pixel-style squares
        ctx.fillRect(-p.w / 2, -p.h / 2, p.w, p.h);
        ctx.restore();
      }

      if (frame < maxFrames) {
        requestAnimationFrame(draw);
      } else {
        ctx.clearRect(0, 0, canvas.width, canvas.height);
      }
    }

    requestAnimationFrame(draw);

    window.addEventListener("resize", function() {
      canvas.width = window.innerWidth;
      canvas.height = window.innerHeight;
    });
  }
  initConfetti();

})();
